Crear partida endpoint, sin websockets. Algo de estructura del codigo. Faltaria usar routers
CarterosFAMAF/LaCosa_Back pull request #1
Opened 2023-09-19 06:27 UTC by mariopicassounc

2023-09-19 19:38 UTC, FNMazzucco commented on src/partida.py
> +        self.turno = (self.turno + 1) % len(self.jugadores)
todos estos metodos son de otros tickets, no los crees por si las dudas, deja que cada la persona a la que le toque implementarla las cree, asi no necesita pisar codigo

2023-09-19 19:39 UTC, FNMazzucco commented on src/partida.py
> +        self.cartas_descarte = None
esto tambien es de otro ticket

2023-09-19 19:40 UTC, FNMazzucco commented on src/models.py
> +    partida_descarte = Required(Partida, reverse="cartas_descarte")
esto es de otro ticket

2023-09-19 19:44 UTC, FNMazzucco requested changes
termina el ticket tranquilo y cuando este listo hacete otra PR

2023-09-19 19:44 UTC, FNMazzucco commented on src/models.py
> +    cartas = Set(Carta)
esto tambien

2023-09-25 18:37 UTC, RAQrodrigo approved these changes

2023-09-25 18:44 UTC, RAQrodrigo approved these changes
piola

2023-09-25 18:45 UTC, FNMazzucco approved these changes

2023-09-25 21:58 UTC, merged